### ISSUE TITLE
[meta] Implement type conversions

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karen-irc/option-t#1328]
## TODO

- `Maybe`
    - [ ] #1345
    - [x] #1346
    - [x] others https://github.com/karen-irc/option-t/pull/1327
- `Nullable`
    - [ ] #1343
    - [x] #1344
    - [x] toMaybe. We should simply assign to `Maybe<T>`
    - [x] others https://github.com/karen-irc/option-t/pull/1327
- `Undefinable`
    - [ ] #1342
    - [x] #1341
    - [x] toMaybe. We should simply assign to `Maybe<T>`
    - [x] others https://github.com/karen-irc/option-t/pull/1327
- `PlainOption`
    - [x] toMaybe: #1331
    - [x] toNullable #1333
    - [x] toUndefinable #1333
    - [x] toPlaintResult. We implemented partially as `okOr()`.
- `PlainResult`
    - [x] toMaybe #1330
    - [x] #1339
    - [x] #1340
    - [x] toOption. We implemented.
