### ISSUE TITLE
Implement `get_or_insert_with()`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karen-irc/option-t#1349]
* https://doc.rust-lang.org/nightly/std/option/enum.Option.html#method.get_or_insert_with

## TODO

- [ ] Implement `get_or_insert_with()` operator for `Maybe`
- [ ] Implement `get_or_insert_with()` operator for `Nullable`
- [ ] Implement `get_or_insert_with()` operator for `Undefinable`
- [ ] Implement `get_or_insert_with()` operator for `PlainOption`

**Comment by tetsuharuohzeki** [comment]
This mutate by self.
We need investigate it's design is safe for JS.

**Comment by tetsuharuohzeki** [comment]
We cannot implement this properly in JS.
