### ISSUE TITLE
Implement `insert()`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karen-irc/option-t#1350]
https://doc.rust-lang.org/nightly/std/option/enum.Option.html#method.insert

## TODO

- [ ] Implement `insert()` operator for `Maybe`
- [ ] Implement `insert()` operator for `Nullable`
- [ ] Implement `insert()` operator for `Undefinable`
- [ ] Implement `insert()` operator for `PlainOption`

**Comment by tetsuharuohzeki** [comment]
This mutate by self.
We need investigate it's design is safe for JS.

**Comment by tetsuharuohzeki** [comment]
We cannot implement this properly in JS.
