### ISSUE TITLE
Consider to implement `then()`/`then_some()` for boolean value

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karen-irc/option-t#1869]
- https://doc.rust-lang.org/std/primitive.bool.html#method.then_some
- https://doc.rust-lang.org/std/primitive.bool.html#method.then

- [ ] Implement `then_some()` for `Maybe<T>`
- [ ] Implement `then_some()` for `Nullable<T>`
- [ ] Implement `then_some()` for `Undefinable<T>`
