### ISSUE TITLE
[meta] Export more items from `option-t/<TypeName>`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karen-irc/option-t#2023]
This tracks items that are not exported currently.

```[tasklist]
### Tasks
- [ ] https://github.com/option-t/option-t/issues/2030
- [ ] https://github.com/option-t/option-t/issues/2031
- [ ] https://github.com/option-t/option-t/issues/2032
- [ ] https://github.com/option-t/option-t/issues/2033
- [ ] https://github.com/option-t/option-t/issues/2034
```

**Comment by tetsuharuohzeki** [comment]
The current tsserver (v5.4)'s autocompletion suggests `option-/<TypeName>` but it does not show up (give up?) more deep path. To work better with intellisense, we want to export more APIs from `option-t/<TypeName>`.
