### ISSUE TITLE
Implement `get_or_insert()`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karen-irc/option-t#374]
* https://doc.rust-lang.org/nightly/std/option/enum.Option.html#method.get_or_insert

## TODO

- [ ] Implement `get_or_insert()` operator for `Maybe`
- [ ] Implement `get_or_insert()` operator for `Nullable`
- [ ] Implement `get_or_insert()` operator for `Undefinable`
- [ ] Implement `get_or_insert()` operator for `PlainOption`

**Comment by tetsuharuohzeki** [comment]
This mutate by self.
We need investigate it's design is safe for JS.

**Comment by tetsuharuohzeki** [comment]
We cannot implement this properly in JS.
