### ISSUE TITLE
[meta] Support ES Module natively

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karen-irc/option-t#421]
After a long time to wait, finally, we would be able to use ES Module natively.
This issue tracks issues to support ES Module as 1st citizen of this package.

## Tasks

1. [x] Should we drop to support versions which does not have support ES Module?
2. [ ] [Set `"type": "module"` to _package.json_.](https://github.com/karen-irc/option-t/issues/816) 
3. [x] Remove `.js` or `.mjs` from `option-t/esm`.
4. [ ] [Reconsider the structure under `option-t/lib`.](https://github.com/karen-irc/option-t/issues/808)

## Related Links

- https://github.com/nodejs/modules

**Comment by saneyuki** [comment]
* [Node.js v13.2.0](https://nodejs.org/en/blog/release/v13.2.0/) unflagged `--experimental-modules`.
   * https://nodejs.org/dist/latest-v13.x/docs/api/esm.html
* They published [Announcing core Node.js support for ECMAScript modules](https://medium.com/@nodejs/announcing-core-node-js-support-for-ecmascript-modules-c5d6dc29b663)

**Comment by saneyuki** [comment]
By these document, _Dual CommonJS/ES module packages_, which we would like to do, we need to wait more times to stabilize `--experimental-conditional-exports`.

**Comment by saneyuki** [comment]
We drop `.js` files from `esm/` by https://github.com/karen-irc/option-t/pull/504

**Comment by saneyuki** [comment]
By https://github.com/karen-irc/option-t/pull/520, we can use `import 'option-t/esm/unwrap.mjs';`

**Comment by saneyuki** [comment]
[In v22](https://github.com/karen-irc/option-t/releases/tag/v22.0.0), we ships to allow import `.mjs`.

**Comment by saneyuki** [comment]
Interestingly, I seem [Node v12.16 supports ESM features natively by backporting them](https://github.com/nodejs/node/pull/31691).
Their backports almost have the same degree of Node.js v13.8

**Comment by saneyuki** [comment]
> Interestingly, I seem Node v12.16 supports ESM features natively by backporting them.
>  Their backports almost have the same degree of Node.js v13.8

By the behavior, it was jump to conclusions.

**Comment by saneyuki** [comment]
* I seem webpack would support `exports` field in [webpack v5 or later](https://github.com/webpack/webpack/issues/9509).
* I [sent a request](https://github.com/rollup/plugins/issues/208) to support `exports` field by rollup plugins.

**Comment by kogai** [comment]
I'm not sure if this is an appropriate request, but could you consider adding `package.json` to the `exports` field?

For example, in the case of using `serverless-plugin-monorepo`.
(FYI: It is a dependencies-resolve-helper for deploying the serverless function which developed as a monorepo package)

It seems trying to resolve `package.json` of each npm packages when resolving dependencies of some monorepo packages.
https://github.com/Butterwire/serverless-plugin-monorepo/blob/82991befe9fd6aeaa37cebf811be4213fa590379/index.js#L59

So if some npm package has defined `exports` field and doesn't define `package.json` in `exports`, `serverless-plugin-monorepo` can’t resolve packages properly.
I think it would be the same for any other npm package that needs to read `package.json`.

**Comment by tetsuharuohzeki** [comment]
@kogai I filed your problem as https://github.com/karen-irc/option-t/issues/726

I’d like to handle this issue separately from this issue because it should be handled as the defail of this task. Feel free to open a new issue from the next time.

**Comment by tetsuharuohzeki** [comment]
webpack v5 supports Node's export fields and [`@rollup/plugin-node-resolve` also supported](https://github.com/rollup/plugins/blob/master/packages/node-resolve/CHANGELOG.md) it in v11.

After esbuild's stable version support it, we can start to drop `lib/` compat dir.

**Comment by tetsuharuohzeki** [comment]
> After esbuild's stable version support it, we can start to drop lib/ compat dir.

This moved to https://github.com/karen-irc/option-t/issues/808

**Comment by tetsuharuohzeki** [comment]
__As a library package__, we have completed to support ES Module. We close this once.
