### ISSUE TITLE
[meta] Obsolete lib/

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karen-irc/option-t#808]
This is a part of https://github.com/karen-irc/option-t/issues/421

## Plan

1. [x] Introduce the flag to publish `lib`/ https://github.com/karen-irc/option-t/pull/810
1. [x] Wait primary linker supports `exports` field.
    - [x] webpack
    - [x] rollup
    - [x] esbuild https://github.com/evanw/esbuild/issues/187
    - [x] TypeScript https://github.com/microsoft/TypeScript/issues/33079
1. [x] Disable the flag to publish `lib/` https://github.com/karen-irc/option-t/issues/811
1. [x] Publish package once. https://github.com/karen-irc/option-t/issues/812
1. [x] Remove codes which creates `lib/` actually. https://github.com/karen-irc/option-t/issues/813

**Comment by tetsuharuohzeki** [comment]
>  We need to wait esbuild before drop this.

TypeScript still have not supported it yet....

**Comment by tetsuharuohzeki** [comment]
[TypeScript 4.5 beta](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/) supports Node.js' `exports` field in package.json.

However, I think we would not able to drop `option-t/lib/***` in near term because TS4.5 only follows `exports` field if tsc's `moduleResolution` is `node12`. Otherwise, tsc will keep the classic behavior which does not follow `exports` field.

If we drop `option-t/lib/***`, this mean that user will need set `moduleResolution` to `node12` but its change forces to user to migrate their project including rewriting a path. This is not smooth migration. So we need to keep `option-t/lib/**`for a while.

**Comment by tetsuharuohzeki** [comment]
[TS 4.5 RC](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-rc/) does not include a support for Nodejs exports field in a stable release.

**Comment by tetsuharuohzeki** [comment]
We dropped almost files under lib/ by #1245.
We may not have to remove `option-t/lib` endpoint.

**Comment by tetsuharuohzeki** [comment]
I shift my mind to that we need to keep this path for backward compatibility and the migration path from legacy toolchain.
So I close this once.
